version: '2'
services:
  web:
      build:
        context: ./
        dockerfile: web.docker
      volumes:
        - ./:/var/www
      ports:
        - "8080:80"
      links:
        - app 
  app:
      build:
        context: ./
        dockerfile: app.docker
      volumes:
        - ./:/var/www
      links:
        - database
        - cache
      environment:
        - "DB_PORT=3306"
        - "DB_HOST=database"
  database:
      image: mysql
      ports:
        - "33061:3306"
      env_file:
        - ./mysql.env
  cache:
    image: memcached